import React, { createContext, useContext, useState } from 'react';

export const LANGUAGES = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', native: 'मराठी' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം' },
  { code: 'or', name: 'Odia', native: 'ଓଡ଼ିଆ' },
];

const UI_STRINGS = {
  en: {
    nav_home: 'Home',
    nav_assistant: 'AI Assistant',
    nav_matcher: 'Find Standard',
    nav_certification: 'Certification Wizard',
    nav_isi: 'Verify ISI Mark',
    nav_huid: 'Verify HUID Gold',
    nav_standards: 'Standards Explorer',
    nav_dashboard: 'Dashboard',
    nav_admin: 'Admin Portal',
    nav_login: 'Login / Portal',
    nav_menu: 'MENU',
    nav_language: 'Language',
    
    // Hero Section
    hero_tag_what: '01 — WHAT IS BISmart AI',
    hero_tag_sih: 'SIH26107 REGULATORY PLATFORM',
    hero_headline_1: 'SMARTER',
    hero_headline_2: 'ACCESS',
    hero_headline_3: 'TO',
    hero_headline_4: 'INDIAN',
    hero_headline_5: 'STANDARDS.',
    hero_desc: 'BISmart AI brings artificial intelligence, standards discovery, product verification, and official Bureau of Indian Standards (BIS) gazette intelligence together into one unified platform.',
    hero_bar: 'DISCOVER · VERIFY · UNDERSTAND',
    hero_btn_assistant: 'Ask AI Assistant',
    hero_btn_standards: 'Find Standard',
    hero_radar_gazette: 'GAZETTE',
    hero_radar_online: 'ONLINE',
    hero_radar_qco: 'QCO: ACTIVE',
    hero_radar_langs: '11 LANGUAGES',
    
    // Stats Section
    stats_tag_what: '01 — What We Are',
    stats_title_1: 'Building',
    stats_title_2: 'Elite',
    stats_title_3: 'Compliance.',
    stats_desc: "India's premier statutory regulatory intelligence ecosystem — engineering high-performance automated verification, laboratory workflows, and grounded clause intelligence for manufacturers, auditors, and citizens.",
    stats_motto: 'Verify · Comply · Certify',
    stats_tag_numbers: '02 — By The Numbers',
    stats_num_is: 'INDIAN STANDARDS (IS)',
    stats_num_qco: 'MANDATORY QCO SCHEMES',
    stats_num_rag: 'GROUNDED RAG PRECISION',
    stats_num_sub: 'STATUTORY SUBSYSTEMS',

    // Timeline Section
    timeline_tag: '03 — BISmart AI WORKFLOW',
    timeline_title_1: 'HOW BISmart AI',
    timeline_title_2: 'WORKS.',
    timeline_step1_title: 'DISCOVER',
    timeline_step1_desc: 'Explore 20,000+ Indian Standards (IS Codes) and mandatory Quality Control Orders (QCOs) for any commercial product category.',
    timeline_step2_title: 'ASK',
    timeline_step2_desc: 'Interact with the intelligent assistant using bilingual voice or text in 11 Indian languages (Hindi, English, Tamil, Punjabi, etc.).',
    timeline_step3_title: 'UNDERSTAND',
    timeline_step3_desc: 'Receive exact clause-level legal grounding with drawer previews of authentic gazetted specifications and laboratory test parameters.',
    timeline_step4_title: 'VERIFY',
    timeline_step4_desc: 'Validate 7-digit ISI CM/L licence numbers and decode 6-character laser-engraved gold HUID hallmarking codes instantly.',

    // AI Section
    ai_tag: '04 — ANTI-HALLUCINATION RETRIEVAL',
    ai_title_1: 'PRECISION OVER',
    ai_title_2: 'PREDICTION.',
    ai_desc: 'Our hybrid semantic vector retrieval searches only authentic Bureau of Indian Standards gazette notifications and Quality Control Orders. Every response includes verifiable clause citations, gazette issue numbers, and official laboratory test methodologies.',
    ai_query_badge: 'EXAMPLE CITIZEN COMPLIANCE QUERY',
    ai_ask_btn: 'Launch Retrieval Engine',

    // Verification Section
    verif_tag: '05 — CITIZEN CONSUMER SAFETY & VERIFICATION',
    verif_title_1: 'UNDERSTAND',
    verif_title_2: 'WHAT YOU',
    verif_title_3: 'ARE BUYING.',
    verif_desc: 'Verify product authenticity before purchase. Validate ISI CM/L licence numbers against official gazette registries and verify gold jewellery 6-character laser HUID hallmarking codes.',
    quick_tab_isi: 'ISI Mark (CM/L)',
    quick_tab_huid: 'Gold Jewellery (HUID)',
    quick_btn_verify: 'Verify License',
    quick_btn_verify_huid: 'Verify HUID',

    // FeatureStack (03 Cards Stack & Circular Arc)
    fs_marquee: 'BISmart Milestones',
    fs_card1_title: 'AI REGULATORY ASSISTANT',
    fs_card1_desc: 'Instant statutory guidance on mandatory Indian Standards, Quality Control Orders, and Scheme-I licensing. Every citation is legally verified against official BIS gazettes.',
    fs_card1_cta: 'Launch Assistant',
    fs_card2_title: 'STANDARDS MATCHER',
    fs_card2_desc: 'Transform commercial product names, raw materials, and capacities into mandatory IS Codes with live enforcement deadlines, testing procedures, and exemption thresholds.',
    fs_card2_cta: 'Find My Standard',
    fs_card3_title: 'PRODUCT VERIFICATION',
    fs_card3_desc: 'Protect Indian households from substandard and counterfeit products. Verify genuine manufacturer CM/L numbers and decode 6-character laser-engraved gold hallmarking codes.',
    fs_card3_cta: 'Verify Authenticity',
    fs_card4_title: '10-STEP CERTIFICATION',
    fs_card4_desc: 'Step-by-step statutory certification roadmap for MSMEs and domestic manufacturers. Tracks testing checklists, STI requirements, and factory audit readiness.',
    fs_card4_cta: 'Start 10-Step Wizard',

    // PhilosophyPortal (04 Expanding 3D Aperture)
    portal_mandate: 'STATUTORY MANDATE',
    portal_title: 'Verify. Comply. Certify.',
    portal_desc: "India’s next-generation statutory regulatory intelligence ecosystem — orchestrating Indian Standards (IS), mandatory Quality Control Orders (QCO), and laboratory testing into verifiable, real-time national certification.",
    portal_domain1: 'STANDARDS COGNITION',
    portal_domain2: 'LABORATORY TESTING & QCO',
    portal_domain3: 'CITIZEN VERIFICATION',
    portal_domain4: 'REGULATORY APIS & SANDBOX',

    // ImpactSection (05 National Regulatory Impact)
    impact_title: 'NATIONAL REGULATORY IMPACT',
    impact_telemetry: 'LIVE TELEMETRY ACTIVE',
    impact_is_label: 'Indian Standards (IS)',
    impact_is_desc: 'Comprehensive national standards corpus catalogued with automated clause-level semantic embeddings and Gazette mirror updates.',
    impact_qco_label: 'Mandatory QCO Schemes',
    impact_qco_desc: 'Active Quality Control Orders enforced across consumer, industrial, and electrical product categories nationwide.',
    impact_precision_label: 'Grounded Precision',
    impact_precision_desc: 'Zero-hallucination statutory verification with exact clause citation hashes and cryptographic audit ledgers.',
    impact_arch_label: 'Statutory Architecture',
    impact_arch_desc: 'End-to-end regulatory pipeline integrating multilingual Indic NLP, laboratory dispatch, and citizen anti-counterfeit scanning.',

    // ScrollChoreography (02 Quadrants Matrix)
    choreo_badge: '05.CHOREOGRAPHY — CITIZEN STATUTORY PROOF MATRIX',
    choreo_title: 'CHOREOGRAPHED REGULATORY PROOFS',
    choreo_subtitle: 'Scroll through the 4 verification quadrants as statutory telemetry converges into the national central authenticity emblem.',
    choreo_step1: '01 SPREAD',
    choreo_step2: '02 DANCE',
    choreo_step3: '03 CONVERGE',
    choreo_step4: '04 HERO EXPAND',
    choreo_q1_title: 'SCHEME-I FACTORY INSPECTION',
    choreo_q1_sub: 'Hydrostatic test bench & thermal safety audit',
    choreo_q2_title: '6-CHAR LASER HUID ASSAY',
    choreo_q2_sub: 'AHC verified gold fineness (22K916 / 18K750)',
    choreo_q3_title: 'STATUTORY QCO MANDATES',
    choreo_q3_sub: 'Cognizable consumer protection under Section 16',
    choreo_q4_title: 'CENTRAL BIS AUTHENTICITY EMBLEM',
    choreo_q4_sub: 'Scroll to expand full verification matrix',

    // Verification Sub-Sections (03, 04, 05.A, 05.B, 06)
    guide_tag: 'CONSUMER FRAUD PREVENTION MATRIX',
    guide_title: 'HOW TO SPOT COUNTERFEIT GOODS & FAKE MARKS',
    guide_subtitle: '4 Critical Inspection Points',
    sim_tag: 'STATUTORY VERIFICATION TEST BENCH',
    sim_title: 'DUAL INTERACTIVE VERIFICATION SIMULATORS',
    sec05a_tag: '05.A — STATUTORY MANDATE & CITIZEN PROTECTION',
    sec05a_title: 'MANDATORY ISI CERTIFICATION',
    sec05a_desc: 'Essential Consumer Categories Mandated by Central Government Quality Control Orders (QCO)',
    sec05b_tag: '05.B — STEP-BY-STEP VERIFICATION PROTOCOL',
    sec05b_title: 'HOW TO VERIFY PRODUCTS',
    sec05b_desc: 'Complete 4-Stage Protocol for Citizens to Detect Substandard Products and Report Fake Marks',
    sec06_tag: '06 — GRIEVANCE REDRESSAL & PENAL ENFORCEMENT',
    sec06_title: 'STATUTORY CONSUMER RIGHTS & ENFORCEMENT HOTLINE',
    sec06_desc: 'Sections 29 & 30 of the Bureau of Indian Standards Act, 2016 impose cognizable penal imprisonment and heavy statutory fines for manufacturing or selling non-certified mandatory goods.',

    // Footer
    footer_org: 'BUREAU OF INDIAN STANDARDS',
    footer_sub: 'MINISTRY OF CONSUMER AFFAIRS, FOOD & PUBLIC DISTRIBUTION • GOVT. OF INDIA',
    footer_rights: 'All Rights Reserved • Smart India Hackathon 2026',
    footer_explore: 'EXPLORE PLATFORM',
    footer_tools: 'REGULATORY TOOLS',
    footer_govt: 'OFFICIAL BIS PORTALS',
    footer_back_top: 'BACK TO TOP',
    footer_bhashini: 'BHASHINI VOICE READY',
    footer_accuracy: '100% REGULATORY ACCURACY',
    demo_badge: 'Smart India Hackathon 2026 Prototype • Demo Data Mode',
  },
  hi: {
    nav_home: 'होम',
    nav_assistant: 'एआई सहायक',
    nav_matcher: 'मानक खोजें',
    nav_certification: 'प्रमाणन विज़ार्ड',
    nav_isi: 'आईएसआई मार्क सत्यापन',
    nav_huid: 'एचयूआईडी स्वर्ण सत्यापन',
    nav_standards: 'भारतीय मानक निर्देशिका',
    nav_dashboard: 'डैशबोर्ड',
    nav_admin: 'प्रशासक पोर्टल',
    nav_login: 'लॉग इन / पोर्टल',
    nav_menu: 'मेन्यू',
    nav_language: 'भाषा',

    // Hero Section
    hero_tag_what: '01 — बीआईएसमार्ट एआई क्या है',
    hero_tag_sih: 'SIH26107 नियामक मंच',
    hero_headline_1: 'सरल',
    hero_headline_2: 'सुलभ',
    hero_headline_3: 'एवं',
    hero_headline_4: 'भारतीय',
    hero_headline_5: 'मानक।',
    hero_desc: 'बीआईएसमार्ट एआई कृत्रिम बुद्धिमत्ता, मानक खोज, उत्पाद सत्यापन और आधिकारिक भारतीय मानक ब्यूरो (BIS) राजपत्र आसूचना को एक एकीकृत मंच पर प्रस्तुत करता है।',
    hero_bar: 'खोजें · सत्यापित करें · समझें',
    hero_btn_assistant: 'एआई सहायक से पूछें',
    hero_btn_standards: 'मानक खोजें',
    hero_radar_gazette: 'राजपत्र',
    hero_radar_online: 'सक्रिय',
    hero_radar_qco: 'क्यूसीओ: सक्रिय',
    hero_radar_langs: '11 भारतीय भाषाएं',

    // Stats Section
    stats_tag_what: '01 — हम कौन हैं',
    stats_title_1: 'सशक्त',
    stats_title_2: 'उत्कृष्ट',
    stats_title_3: 'अनुपालन।',
    stats_desc: 'भारत का अग्रणी विधिक नियामक आसूचना तंत्र — निर्माताओं, लेखापरीक्षकों और नागरिकों के लिए उच्च-प्रदर्शन स्वचालित सत्यापन और खंड-स्तरीय कानूनी ज्ञान।',
    stats_motto: 'सत्यापित · अनुपालन · प्रमाणन',
    stats_tag_numbers: '02 — मुख्य आंकड़े',
    stats_num_is: 'भारतीय मानक (IS)',
    stats_num_qco: 'अनिवार्य QCO योजनाएं',
    stats_num_rag: 'सटीक RAG प्रामाणिकता',
    stats_num_sub: 'विधिक उप-प्रणालियां',

    // Timeline Section
    timeline_tag: '03 — बीआईएसमार्ट एआई कार्यप्रणाली',
    timeline_title_1: 'बीआईएसमार्ट एआई',
    timeline_title_2: 'कैसे काम करता है।',
    timeline_step1_title: 'खोजें',
    timeline_step1_desc: 'किसी भी उत्पाद श्रेणी के लिए 20,000+ भारतीय मानक (IS कोड) और अनिवार्य गुणवत्ता नियंत्रण आदेश (QCO) खोजें।',
    timeline_step2_title: 'पूछें',
    timeline_step2_desc: '11 भारतीय भाषाओं में आवाज या टेक्स्ट के साथ आधिकारिक एआई सहायक से तत्काल विधिक परामर्श प्राप्त करें।',
    timeline_step3_title: 'समझें',
    timeline_step3_desc: 'प्रामाणिक राजपत्रित विनिर्देशों और प्रयोगशाला परीक्षण मापदंडों के साथ सटीक खंड-स्तरीय कानूनी आधार देखें।',
    timeline_step4_title: 'सत्यापित करें',
    timeline_step4_desc: '7-अंकीय आईएसआई सीएम/एल लाइसेंस नंबर और 6-वर्ण लेजर-उत्कीर्ण स्वर्ण एचयूआईडी कोड तुरंत सत्यापित करें।',

    // AI Section
    ai_tag: '04 — प्रामाणिक पुनर्प्राप्ति',
    ai_title_1: 'सटीकता',
    ai_title_2: 'प्राथमिकता।',
    ai_desc: 'हमारा हाइब्रिड सिमेंटिक वेक्टर इंजन केवल आधिकारिक भारतीय मानक ब्यूरो राजपत्र अधिसूचनाओं और गुणवत्ता नियंत्रण आदेशों में खोज करता है। प्रत्येक उत्तर में प्रमाणित खंड संदर्भ और प्रयोगशाला परीक्षण पद्धतियां शामिल हैं।',
    ai_query_badge: 'नागरिक अनुपालन प्रश्न उदाहरण',
    ai_ask_btn: 'पुनर्प्राप्ति इंजन चलाएं',

    // Verification Section
    verif_tag: '05 — नागरिक उपभोक्ता सुरक्षा और सत्यापन',
    verif_title_1: 'खरीदने से पहले',
    verif_title_2: 'मानक की',
    verif_title_3: 'जांच करें।',
    verif_desc: 'खरीदने से पहले उत्पाद प्रामाणिकता सत्यापित करें। आधिकारिक राजपत्र रजिस्टरों में आईएसआई सीएम/एल लाइसेंस नंबर और स्वर्ण आभूषण के 6-वर्ण लेजर एचयूआईडी हॉलमार्किंग कोड की पुष्टि करें।',
    quick_tab_isi: 'आईएसआई मार्क (CM/L)',
    quick_tab_huid: 'स्वर्ण आभूषण (HUID)',
    quick_btn_verify: 'लाइसेंस सत्यापित करें',
    quick_btn_verify_huid: 'एचयूआईडी सत्यापित करें',

    // FeatureStack (03 Cards Stack & Circular Arc)
    fs_marquee: 'बीआईएसमार्ट उपलब्धियां',
    fs_card1_title: 'एआई नियामक सहायक',
    fs_card1_desc: 'अनिवार्य भारतीय मानकों, गुणवत्ता नियंत्रण आदेशों (QCO) और स्कीम-I लाइसेंसिंग पर तत्काल विधिक मार्गदर्शन। प्रत्येक उद्धरण आधिकारिक बीआईएस राजपत्रों से सत्यापित है।',
    fs_card1_cta: 'एआई सहायक शुरू करें',
    fs_card2_title: 'मानक खोजक',
    fs_card2_desc: 'वाणिज्यिक उत्पाद नामों, कच्चे माल और क्षमताओं को लाइव प्रवर्तन समय-सीमा और परीक्षण प्रक्रियाओं के साथ अनिवार्य आईएस कोड में बदलें।',
    fs_card2_cta: 'मानक खोजें',
    fs_card3_title: 'उत्पाद सत्यापन',
    fs_card3_desc: 'भारतीय परिवारों को घटिया और नकली उत्पादों से सुरक्षित रखें। निर्माता सीएम/एल नंबर और स्वर्ण हॉलमार्किंग कोड सत्यापित करें।',
    fs_card3_cta: 'प्रामाणिकता जांचें',
    fs_card4_title: '10-चरणीय प्रमाणन',
    fs_card4_desc: 'एमएसएमई और घरेलू निर्माताओं के लिए चरण-दर-चरण विधिक प्रमाणन रोडमैप। परीक्षण चेकलिस्ट और ऑडिट तैयारी ट्रैक करें।',
    fs_card4_cta: 'विज़ार्ड शुरू करें',

    // PhilosophyPortal (04 Expanding 3D Aperture)
    portal_mandate: 'विधिक अधिदेश',
    portal_title: 'सत्यापित करें. अनुपालन करें. प्रमाणित करें.',
    portal_desc: 'भारत का अगली पीढ़ी का विधिक नियामक आसूचना तंत्र — भारतीय मानकों (IS), अनिवार्य गुणवत्ता नियंत्रण आदेशों (QCO) और प्रयोगशाला परीक्षणों का वास्तविक समय सत्यापन।',
    portal_domain1: 'मानक संज्ञान',
    portal_domain2: 'प्रयोगशाला परीक्षण एवं QCO',
    portal_domain3: 'नागरिक सत्यापन',
    portal_domain4: 'नियामक एपीआई एवं सैंडबॉक्स',

    // ImpactSection (05 National Regulatory Impact)
    impact_title: 'राष्ट्रीय नियामक प्रभाव',
    impact_telemetry: 'लाइव टेलीमेट्री सक्रिय',
    impact_is_label: 'भारतीय मानक (IS)',
    impact_is_desc: 'स्वचालित खंड-स्तरीय सिमेंटिक एम्बेडिंग और राजपत्र अपडेट के साथ 20,000+ राष्ट्रीय मानकों की संपूर्ण निर्देशिका।',
    impact_qco_label: 'अनिवार्य QCO योजनाएं',
    impact_qco_desc: 'देश भर में उपभोक्ता, औद्योगिक और विद्युत उत्पाद श्रेणियों में लागू अनिवार्य गुणवत्ता नियंत्रण आदेश।',
    impact_precision_label: 'प्रमाणित सटीकता',
    impact_precision_desc: 'सटीक खंड उद्धरण और ऑडिट बहीखातों के साथ 100% शून्य-भ्रांति विधिक सत्यापन।',
    impact_arch_label: 'विधिक संरचना',
    impact_arch_desc: 'बहुभाषी भारतीय एनएलपी, प्रयोगशाला प्रेषण और नागरिक नकली-रोधी स्कैनिंग को एकीकृत करने वाली संपूर्ण नियामक प्रणाली।',

    // ScrollChoreography (02 Quadrants Matrix)
    choreo_badge: '05.कोरियोग्राफी — नागरिक विधिक प्रमाण मैट्रिक्स',
    choreo_title: 'संयोजित नियामक प्रमाण',
    choreo_subtitle: '4 सत्यापन क्षेत्रों के माध्यम से स्क्रॉल करें जैसे ही विधिक डेटा राष्ट्रीय केंद्रीय प्रामाणिकता प्रतीक में परिवर्तित होता है।',
    choreo_step1: '01 प्रसार',
    choreo_step2: '02 गति',
    choreo_step3: '03 अभिसरण',
    choreo_step4: '04 पूर्ण दृश्य',
    choreo_q1_title: 'स्कीम-I कारखाना निरीक्षण',
    choreo_q1_sub: 'हाइड्रोस्टैटिक परीक्षण और थर्मल सुरक्षा ऑडिट',
    choreo_q2_title: '6-वर्ण लेजर HUID परीक्षण',
    choreo_q2_sub: 'AHC सत्यापित स्वर्ण शुद्धता (22K916 / 18K750)',
    choreo_q3_title: 'विधिक QCO अधिदेश',
    choreo_q3_sub: 'धारा 16 के तहत संज्ञेय उपभोक्ता संरक्षण',
    choreo_q4_title: 'केंद्रीय बीआईएस प्रामाणिकता प्रतीक',
    choreo_q4_sub: 'राष्ट्रीय सत्यापन मैट्रिक्स में विधिक अभिसरण',

    // Verification Sub-Sections (03, 04, 05.A, 05.B, 06)
    guide_tag: 'उपभोक्ता धोखाधड़ी रोकथाम मैट्रिक्स',
    guide_title: 'नकली सामान और जाली चिह्नों की पहचान कैसे करें',
    guide_subtitle: '4 महत्वपूर्ण निरीक्षण बिंदु',
    sim_tag: 'विधिक सत्यापन परीक्षण बेंच',
    sim_title: 'दोहरे इंटरएक्टिव सत्यापन सिमुलेटर',
    sec05a_tag: '05.A — विधिक अधिदेश एवं नागरिक सुरक्षा',
    sec05a_title: 'अनिवार्य आईएसआई प्रमाणन',
    sec05a_desc: 'केंद्र सरकार के गुणवत्ता नियंत्रण आदेशों (QCO) द्वारा अनिवार्य आवश्यक उपभोक्ता श्रेणियां',
    sec05b_tag: '05.B — चरण-दर-चरण सत्यापन प्रोटोकॉल',
    sec05b_title: 'उत्पादों का सत्यापन कैसे करें',
    sec05b_desc: 'घटिया उत्पादों का पता लगाने और नकली चिह्नों की रिपोर्ट करने के लिए नागरिकों के लिए पूर्ण 4-चरणीय प्रोटोकॉल',
    sec06_tag: '06 — शिकायत निवारण एवं दंडात्मक प्रवर्तन',
    sec06_title: 'विधिक उपभोक्ता अधिकार एवं प्रवर्तन हेल्पलाइन',
    sec06_desc: 'भारतीय मानक ब्यूरो अधिनियम, 2016 की धारा 29 और 30 गैर-प्रमाणित अनिवार्य सामानों के निर्माण या बिक्री पर कारावास और भारी विधिक जुर्माना लगाती है।',

    // Footer
    footer_org: 'भारतीय मानक ब्यूरो',
    footer_sub: 'उपभोक्ता मामले, खाद्य और सार्वजनिक वितरण मंत्रालय • भारत सरकार',
    footer_rights: 'सर्वाधिकार सुरक्षित • स्मार्ट इंडिया हैकाथॉन 2026',
    footer_explore: 'मंच अन्वेषण',
    footer_tools: 'नियामक उपकरण',
    footer_govt: 'आधिकारिक बीआईएस पोर्टल',
    footer_back_top: 'शीर्ष पर जाएं',
    footer_bhashini: 'भाषिणी आवाज समर्थित',
    footer_accuracy: '100% विधिक सटीकता',
    demo_badge: 'स्मार्ट इंडिया हैकाथॉन 2026 प्रोटोटाइप • डेमो डेटा मोड',
  },
  pa: {
    nav_home: 'ਘਰ',
    nav_assistant: 'ਏਆਈ ਸਹਾਇਕ',
    nav_matcher: 'ਮਿਆਰ ਲੱਭੋ',
    nav_certification: 'ਪ੍ਰਮਾਣੀਕਰਣ ਵਿਜ਼ਾਰਡ',
    nav_isi: 'ਆਈਐਸਆਈ ਮਾਰਕ ਤਸਦੀਕ',
    nav_huid: 'ਸੋਨਾ ਐਚਯੂਆਈਡੀ ਤਸਦੀਕ',
    nav_standards: 'ਮਿਆਰ ਐਕਸਪਲੋਰਰ',
    nav_menu: 'ਮੀਨੂ',
    nav_language: 'ਭਾਸ਼ਾ',
    hero_headline_1: 'ਸਮਾਰਟ',
    hero_headline_2: 'ਪਹੁੰਚ',
    hero_headline_3: 'ਭਾਰਤੀ',
    hero_headline_4: 'ਮਿਆਰਾਂ',
    hero_headline_5: 'ਵੱਲ।',
    hero_desc: 'ਬੀਆਈਐਸਮਾਰਟ ਏਆਈ ਭਾਰਤੀ ਮਿਆਰਾਂ, ਉਤਪਾਦ ਤਸਦੀਕ ਅਤੇ ਬੀਆਈਐਸ ਗਜ਼ਟ ਜਾਣਕਾਰੀ ਨੂੰ ਇੱਕੋ ਥਾਂ ਪੇਸ਼ ਕਰਦਾ ਹੈ।',
    hero_btn_assistant: 'ਏਆਈ ਸਹਾਇਕ ਨੂੰ ਪੁੱਛੋ',
    hero_btn_standards: 'ਮਿਆਰ ਲੱਭੋ',
    stats_motto: 'ਤਸਦੀਕ ਕਰੋ · ਪਾਲਣਾ ਕਰੋ · ਪ੍ਰਮਾਣਿਤ ਕਰੋ',
    footer_org: 'ਭਾਰਤੀ ਮਿਆਰ ਬਿਊਰੋ',
  },
  ta: {
    nav_home: 'முகப்பு',
    nav_assistant: 'AI உதவியாளர்',
    nav_matcher: 'தரநிலையைக் கண்டறிக',
    nav_certification: 'சான்றிதழ் வழிகாட்டி',
    nav_isi: 'ISI முத்திரை சரிபார்ப்பு',
    nav_huid: 'தங்க HUID சரிபார்ப்பு',
    nav_standards: 'தரநிலைகள் உலாவி',
    nav_menu: 'பட்டியல்',
    nav_language: 'மொழி',
    hero_headline_1: 'இந்திய',
    hero_headline_2: 'தரநிலைகளுக்கு',
    hero_headline_3: 'புத்திசாலித்தனமான',
    hero_headline_4: 'அணுகல்',
    hero_headline_5: 'முறை.',
    hero_desc: 'BISmart AI செயற்கை நுண்ணறிவு, தரநிலை கண்டறிதல், தயாரிப்பு சரிபார்ப்பு மற்றும் அதிகாரப்பூர்வ BIS வழிகாட்டுதல்களை ஒரே தளத்தில் கொண்டுவருகிறது.',
    hero_btn_assistant: 'AI உதவியாளரிடம் கேளுங்கள்',
    hero_btn_standards: 'தரநிலையைக் கண்டறியவும்',
    stats_motto: 'சரிபார் · இணங்கு · சான்றிதழ் பெறு',
    footer_org: 'இந்திய தரநிலைகள் பணியகம்',
  },
  te: {
    nav_home: 'హోమ్',
    nav_assistant: 'AI సహాయకుడు',
    nav_matcher: 'ప్రమాణాన్ని కనుగొనండి',
    nav_certification: 'ధృవీకరణ విజార్డ్',
    nav_isi: 'ISI మార్క్ ధృవీకరణ',
    nav_huid: 'గోల్డ్ HUID ధృవీకరణ',
    nav_standards: 'ప్రమాణాల ఎక్స్‌ప్లోరర్',
    nav_menu: 'మెనూ',
    nav_language: 'భాష',
    hero_headline_1: 'భారతీయ',
    hero_headline_2: 'ప్రమాణాలకు',
    hero_headline_3: 'తెలివైన',
    hero_headline_4: 'సులభమైన',
    hero_headline_5: 'యాక్సెస్.',
    hero_desc: 'BISmart AI కృత్రిమ మేధస్సు, భారతీయ ప్రమాణాల శోధన మరియు ప్రామాణికతను ఒకే వేదికపైకి తెస్తుంది.',
    hero_btn_assistant: 'AI సహాయకుడిని అడగండి',
    hero_btn_standards: 'ప్రమాణాన్ని కనుగొనండి',
    stats_motto: 'ధృవీకరించండి · పాటించండి · సర్టిఫై చేయండి',
    footer_org: 'బ్యూరో ఆఫ్ ఇండియన్ స్టాండర్డ్స్',
  },
  bn: {
    nav_home: 'হোম',
    nav_assistant: 'এআই সহকারী',
    nav_matcher: 'মান সন্ধান করুন',
    nav_certification: 'সার্টিফিকেশন উইজার্ড',
    nav_isi: 'আইএসআই মার্ক যাচাইকরণ',
    nav_huid: 'স্বর্ণ HUID যাচাইকরণ',
    nav_standards: 'মান এক্সপ্লোরার',
    nav_menu: 'মেনু',
    nav_language: 'ভাষা',
    hero_headline_1: 'ভারতীয়',
    hero_headline_2: 'মানদণ্ডে',
    hero_headline_3: 'সহজ',
    hero_headline_4: 'স্মার্ট',
    hero_headline_5: 'প্রবেশাধিকার।',
    hero_desc: 'BISmart AI কৃত্রিম বুদ্ধিমত্তা, ভারতীয় মান অনুসন্ধান এবং পণ্য যাচাইকরণকে এক প্ল্যাটফর্মে একত্রিত করে।',
    hero_btn_assistant: 'এআই সহকারীকে জিজ্ঞাসা করুন',
    hero_btn_standards: 'মান খুঁজুন',
    stats_motto: 'যাচাই করুন · মেনে চলুন · প্রত্যয়িত করুন',
    footer_org: 'ভারতীয় মান ব্যুরো',
  },
  mr: {
    nav_home: 'मुख्यपृष्ठ',
    nav_assistant: 'एआय सहाय्यक',
    nav_matcher: 'मानके शोधा',
    nav_certification: 'प्रमाणीकरण विझार्ड',
    nav_isi: 'ISI मार्क पडताळणी',
    nav_huid: 'सुवर्ण HUID पडताळणी',
    nav_standards: 'मानके एक्सप्लोरर',
    nav_menu: 'मेनू',
    nav_language: 'भाषा',
    hero_headline_1: 'भारतीय',
    hero_headline_2: 'मानकांसाठी',
    hero_headline_3: 'स्मार्ट',
    hero_headline_4: 'सुलभ',
    hero_headline_5: 'प्रवेश.',
    hero_desc: 'BISmart AI कृत्रिम बुद्धिमत्ता, मानके शोध आणि उत्पादन पडताळणी एकाच व्यासपीठावर आणते.',
    hero_btn_assistant: 'एआय सहाय्यकाला विचारा',
    hero_btn_standards: 'मानक शोधा',
    stats_motto: 'पडताळा · पालन करा · प्रमाणित करा',
    footer_org: 'भारतीय मानक ब्युरो',
  },
  gu: {
    nav_home: 'હોમ',
    nav_assistant: 'AI સહાયક',
    nav_matcher: 'ધોરણો શોધો',
    nav_certification: 'પ્રમાણીકરણ વિઝાર્ડ',
    nav_isi: 'ISI માર્ક ચકાસણી',
    nav_huid: 'સોનાની HUID ચકાસણી',
    nav_standards: 'ધોરણો એક્સપ્લોરર',
    nav_menu: 'મેનુ',
    nav_language: 'ભાષા',
    hero_headline_1: 'ભારતીય',
    hero_headline_2: 'માનકો',
    hero_headline_3: 'માટે',
    hero_headline_4: 'સ્માર્ટ',
    hero_headline_5: 'ઍક્સેસ.',
    hero_desc: 'BISmart AI કૃત્રિમ બુદ્ધિ, ભારતીય ધોરણોની શોધ અને ઉત્પાદન ચકાસણીને એક પ્લેટફોર્મ પર લાવે છે.',
    hero_btn_assistant: 'AI સહાયકને પૂછો',
    hero_btn_standards: 'માનક શોધો',
    stats_motto: 'ચકાસો · પાલન કરો · પ્રમાણિત કરો',
    footer_org: 'ભારતીય માનક બ્યુરો',
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [currentLang, setCurrentLang] = useState('en');

  const t = (key) => {
    if (UI_STRINGS[currentLang] && UI_STRINGS[currentLang][key]) {
      return UI_STRINGS[currentLang][key];
    }
    return UI_STRINGS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLang, setCurrentLang, languages: LANGUAGES, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
